In [39]:
# From your virtul environment, install the pandas package for working with data frames: 
# pip install pandas
# pandas is an open source Python library for data analysis
# A data frame allows us to read and access data stored in spreadsheet (.csv) format
# Good tutorial on pandas: http://pandas.pydata.org/pandas-docs/stable/10min.html
# Pandas Cookbook: http://pandas.pydata.org/pandas-docs/stable/tutorials.html
# Another good resource for pandas: http://chrisalbon.com/python/pandas_dataframe_importing_csv.htm

#Import the required packages
#Import package pandas for data analysis
import pandas as pd

# Import package numpy for numeric computing
import numpy as np

# Import package matplotlib for visualisation/plotting jjo
import matplotlib.pyplot as plt

#For showing plots directly in the notebook run the command below
%matplotlib inline

# For saving multiple plots into a single pdf file
from matplotlib.backends.backend_pdf import PdfPages

In [3]:
import pandas as pd

# Now this will work
df = pd.read_csv('/Users/jennifercasavantes/Downloads/Alone_or_in_Any_Combination.csv', 
                 keep_default_na=True, 
                 delimiter=',', 
                 skipinitialspace=True)

pd.set_option('display.max_rows', 100)

/var/folders/5m/lm7lkjcj0091slj1knvhj6g00000gn/T/ipykernel_38197/2577764226.py:4: DtypeWarning: Columns (3,14,20,28,30,32,38,42,44,58,60,62,69,71,73,77,79,81,83,89,91,93,99,117,119,121,123,125,127,129,133,139,141,143,145,147,149,153,155,161,165,171,173,177,183,193,195,197,206,208,212,214,218,220,224,226,232,236,238,242,248,256,270,273,279,281,285,289,291,293,295,297,299,315,319,341,347,355) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/Users/jennifercasavantes/Downloads/Alone_or_in_Any_Combination.csv',

In [4]:
# Check how many rows and columns this dataframe has
df_filtered = df[(df["Borough"] == "Manhattan")]

In [5]:
df.dtypes

Orig Order     float64
GeoType         object
Borough         object
GeoID           object
BCT2020        float64
                ...
Asian.82        object
Asian.83       float64
Asian.84        object
Asian.85       float64
Total Asian     object
Length: 358, dtype: object

In [6]:
#another way to get a summary of columns
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2718 entries, 0 to 2717
Columns: 358 entries, Orig Order to Total Asian
dtypes: float64(194), object(164)
memory usage: 7.4+ MB

In [7]:
# Look at column names. Some have spaces in or after the name, e.g., 'Insurance Type '.
df.columns

Index(['Orig Order', 'GeoType', 'Borough', 'GeoID', 'BCT2020', 'GeoName',
       'CDType', 'NTAType', 'Pop', 'PopP',
       ...
       'Asian.77', 'Asian.78', 'Asian.79', 'Asian.80', 'Asian.81', 'Asian.82',
       'Asian.83', 'Asian.84', 'Asian.85', 'Total Asian'],
      dtype='object', length=358)

In [8]:
print(df["Borough"].unique())
print(df["GeoType"].unique())

['New York City' 'Manhattan' 'Bronx' 'Brooklyn' 'Queens' 'Staten Island'
 'Manhattan, Bronx' 'Queens, Bronx' 'Brooklyn, Queens'
 'Staten Island, Brooklyn' nan]
['City2020' 'Boro2020' 'CT2020' 'NTA2020' 'CDTA2020' 'CCD2023' nan]

In [9]:
df["GeoType"] = df["GeoType"].astype(str).str.strip()
df["Borough"] = df["Borough"].astype(str).str.strip()

In [10]:
# Strip leading/trailing spaces and extra quotes, and lowercase everything
df["Borough"] = df["Borough"].astype(str).str.strip().str.strip("'").str.lower()
df["GeoType"] = df["GeoType"].astype(str).str.strip().str.strip("'").str.lower()

In [11]:
df_filtered = df[(df["GeoType"] == "ct2020") & (df["Borough"] == "manhattan")]
print(df_filtered.head())
print("Rows found:", len(df_filtered))

      Orig Order GeoType    Borough        GeoID    BCT2020 GeoName  CDType  \
1172      1173.0  ct2020  manhattan  36061000100  1000100.0     NaN     NaN
1173      1174.0  ct2020  manhattan  36061000201  1000201.0     NaN     NaN
1174      1175.0  ct2020  manhattan  36061000202  1000202.0     NaN     NaN
1175      1176.0  ct2020  manhattan  36061000500  1000500.0     NaN     NaN
1176      1177.0  ct2020  manhattan  36061000600  1000600.0     NaN     NaN

      NTAType     Pop   PopP  ... Asian.77  Asian.78 Asian.79  Asian.80  \
1172      NaN       0  100.0  ...      NaN       NaN      NaN       NaN
1173      NaN   2,012  100.0  ...      NaN       NaN      NaN       NaN
1174      NaN   7,266  100.0  ...      NaN       NaN      NaN       NaN
1175      NaN       5  100.0  ...      NaN       NaN      NaN       NaN
1176      NaN  11,616  100.0  ...      NaN       NaN      NaN       NaN

     Asian.81  Asian.82 Asian.83  Asian.84 Asian.85  Total Asian
1172      NaN       NaN      NaN       NaN      NaN            0
1173      NaN       NaN      NaN       NaN      NaN        1,355
1174      NaN       NaN      NaN       NaN      NaN        3,582
1175      NaN       NaN      NaN       NaN      NaN            0
1176      NaN        35      0.3       172      1.5       11,796

[5 rows x 358 columns]
Rows found: 310

In [12]:
df_filtered.head()

,Orig Order,GeoType,Borough,GeoID,BCT2020,GeoName,CDType,NTAType,Pop,PopP,...,Asian.77,Asian.78,Asian.79,Asian.80,Asian.81,Asian.82,Asian.83,Asian.84,Asian.85,Total Asian
1172,1173.0,ct2020,manhattan,36061000100,1000100.0,NaN,NaN,NaN,0,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1173,1174.0,ct2020,manhattan,36061000201,1000201.0,NaN,NaN,NaN,"2,012",100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"1,355"
1174,1175.0,ct2020,manhattan,36061000202,1000202.0,NaN,NaN,NaN,"7,266",100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"3,582"
1175,1176.0,ct2020,manhattan,36061000500,1000500.0,NaN,NaN,NaN,5,100.0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0
1176,1177.0,ct2020,manhattan,36061000600,1000600.0,NaN,NaN,NaN,"11,616",100.0,...,NaN,NaN,NaN,NaN,NaN,35,0.3,172,1.5,"11,796"

In [13]:
for col in df_filtered.columns:
    if "White" in col or "Black" in col or "Asian" in col or "Hispanic" or "Pop" in col:
        print(col)

Orig Order
GeoType
Borough
GeoID
BCT2020
GeoName
CDType
NTAType
Pop
PopP
Hispanic
Hispanic.1
Hispanic.2
Hispanic.3
Hispanic.4
Hispanic.5
Hispanic.6
Hispanic.7
Hispanic.8
Hispanic.9
Hispanic.10
Hispanic.11
Hispanic.12
Hispanic.13
Hispanic.14
Hispanic.15
Hispanic.16
Hispanic.17
Hispanic.18
Hispanic.19
Hispanic.20
Hispanic.21
Hispanic.22
Hispanic.23
Hispanic.24
Hispanic.25
Hispanic.26
Hispanic.27
Hispanic.28
Hispanic.29
Hispanic.30
Hispanic.31
Hispanic.32
Hispanic.33
Hispanic.34
Hispanic.35
Hispanic.36
Hispanic.37
Hispanic.38
Hispanic.39
Hispanic.40
Hispanic.41
Hispanic.42
Hispanic.43
Hispanic.44
Hispanic.45
Hispanic.46
Hispanic.47
Hispanic.48
Hispanic.49
Hispanic.50
Hispanic.51
Hispanic.52
Hispanic.53
Total Hispanic
White
White .1
White .2
White .3
White .4
White .5
White .6
White .7
White .8
White .9
White .10
White .11
White .12
White .13
White .14
White .15
White .16
White .17
White .18
White .19
White .20
White .21
White .22
White .23
White .24
White .25
White .26
White .27
White .28
White .29
White .30
White .31
White .32
White .33
White .34
White .35
White .36
White .37
White .38
White .39
White .40
White .41
White .42
White .43
White .44
White .45
White .46
White .47
White .48
White .49
White .50
White .51
White .52
White .53
White .54
White .55
White .56
White .57
White .58
White .59
White .60
White .61
White .62
White .63
White .64
White .65
White .66
White .67
White .68
White .69
White .70
White .71
White .72
White .73
White .74
White .75
White .76
White .77
White .78
White .79
White .80
White .81
White .82
White .83
White .84
White .85
White .86
White .87
White .88
White .89
White .90
White .91
White .92
White .93
White .94
White .95
White .96
White .97
White .98
White .99
White .100
White .101
White .102
White .103
White .104
White .105
White .106
White .107
White .108
White .109
White .110
White .111
White .112
White .113
White .114
White .115
White .116
White .117
White .118
White .119
White .120
White .121
White .122
White .123
White .124
White .125
White .126
White .127
White .128
White .129
White .130
White .131
White .132
White .133
White .134
White .135
Total White
Black
Black.1
Black.2
Black.3
Black.4
Black.5
Black.6
Black.7
Black.8
Black.9
Black.10
Black.11
Black.12
Black.13
Black.14
Black.15
Black.16
Black.17
Black.18
Black.19
Black.20
Black.21
Black.22
Black.23
Black.24
Black.25
Black.26
Black.27
Black.28
Black.29
Black.30
Black.31
Black.32
Black.33
Black.34
Black.35
Black.36
Black.37
Black.38
Black.39
Black.40
Black.41
Black.42
Black.43
Black.44
Black.45
Black.46
Black.47
Black.48
Black.49
Black.50
Black.51
Black.52
Black.53
Black.54
Black.55
Black.56
Black.57
Black.58
Black.59
Black.60
Black.61
Black.62
Black.63
Black.64
Black.65
Black.66
Black.67
Total Black
Asian
Asian.1
Asian.2
Asian.3
Asian.4
Asian.5
Asian.6
Asian.7
Asian.8
Asian.9
Asian.10
Asian.11
Asian.12
Asian.13
Asian.14
Asian.15
Asian.16
Asian.17
Asian.18
Asian.19
Asian.20
Asian.21
Asian.22
Asian.23
Asian.24
Asian.25
Asian.26
Asian.27
Asian.28
Asian.29
Asian.30
Asian.31
Asian.32
Asian.33
Asian.34
Asian.35
Asian.36
Asian.37
Asian.38
Asian.39
Asian.40
Asian.41
Asian.42
Asian.43
Asian.44
Asian.45
Asian.46
Asian.47
Asian.48
Asian.49
Asian.50
Asian.51
Asian.52
Asian.53
Asian.54
Asian.55
Asian.56
Asian.57
Asian.58
Asian.59
Asian.60
Asian.61
Asian.62
Asian.63
Asian.64
Asian.65
Asian.66
Asian.67
Asian.68
Asian.69
Asian.70
Asian.71
Asian.72
Asian.73
Asian.74
Asian.75
Asian.76
Asian.77
Asian.78
Asian.79
Asian.80
Asian.81
Asian.82
Asian.83
Asian.84
Asian.85
Total Asian

In [15]:
keep = ['White ', 'Black', 'Asian', 'Hispanic', 'Pop']
demo_tract = df[keep].copy()

In [16]:
print(demo_tract.columns)

Index(['White ', 'Black', 'Asian', 'Hispanic', 'Pop'], dtype='object')

In [17]:


# Load the dataset
#df = pd.read_csv("/Users/jennifercasavantes/Downloads/Alone_or_in_Any_Combination.csv")

# Convert all columns to numeric where possible
df = df.apply(pd.to_numeric, errors='ignore')

# Step 1: Identify columns that contain each category
white_cols = [col for col in df.columns if 'White ' in col]
black_cols = [col for col in df.columns if 'Black or African American' in col]
asian_cols = [col for col in df.columns if 'Asian' in col]
hispanic_cols = [col for col in df.columns if 'Hispanic' in col]

# Step 2: Sum columns by group
df['White '] = df[white_cols].apply(pd.to_numeric, errors='coerce').sum(axis=1)
df['Black'] = df[black_cols].apply(pd.to_numeric, errors='coerce').sum(axis=1)
df['Asian'] = df[asian_cols].apply(pd.to_numeric, errors='coerce').sum(axis=1)
df['Hispanic'] = df[hispanic_cols].apply(pd.to_numeric, errors='coerce').sum(axis=1)

# Step 3: Use total population column (you can confirm exact name here)
pop_col = [col for col in df.columns if "Pop" in col or "Total" in col][0]
df['Pop'] = pd.to_numeric(df[pop_col], errors='coerce')

# Step 4: Compute percentages
df['% White'] = df['White '] / df['Pop']
df['% Black'] = df['Black'] / df['Pop']
df['% Asian'] = df['Asian'] / df['Pop']
df['% Hispanic'] = df['Hispanic'] / df['Pop']

# Step 5: Keep relevant results
demo_tract = df[['White ', 'Black', 'Asian', 'Hispanic', 'Pop', '% White', '% Black', '% Asian', '% Hispanic']]

# Display first rows
print(demo_tract.head())

    White   Black   Asian  Hispanic  Pop  % White  % Black  % Asian  \
0   4535.5    0.0  4343.9      50.4  NaN      NaN      NaN      NaN
1  11173.3    0.0  4146.4    3964.9  NaN      NaN      NaN      NaN
2  14329.3    0.0  7762.8    2427.1  NaN      NaN      NaN      NaN
3  11969.6    0.0  7147.9    2193.7  NaN      NaN      NaN      NaN
4  13624.6    0.0  3599.0     849.0  NaN      NaN      NaN      NaN

   % Hispanic
0         NaN
1         NaN
2         NaN
3         NaN
4         NaN

/var/folders/5m/lm7lkjcj0091slj1knvhj6g00000gn/T/ipykernel_38197/185991216.py:4: DtypeWarning: Columns (3,14,20,28,30,32,38,42,44,58,60,62,69,71,73,77,79,81,83,89,91,93,99,117,119,121,123,125,127,129,133,139,141,143,145,147,149,153,155,161,165,171,173,177,183,193,195,197,206,208,212,214,218,220,224,226,232,236,238,242,248,256,270,273,279,281,285,289,291,293,295,297,299,315,319,341,347,355) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv("/Users/jennifercasavantes/Downloads/Alone_or_in_Any_Combination.csv")
/var/folders/5m/lm7lkjcj0091slj1knvhj6g00000gn/T/ipykernel_38197/185991216.py:7: FutureWarning: errors='ignore' is deprecated and will raise in a future version. Use to_numeric without passing `errors` and catch exceptions explicitly instead
  df = df.apply(pd.to_numeric, errors='ignore')

In [18]:
import pandas as pd

# Load your CSV file
df = pd.read_csv("/Users/jennifercasavantes/Downloads/Alone_or_in_Any_Combination.csv")

# Compute total population per row
df["Pop"] = df[["White", "Black", "Asian", "Hispanic"]].sum(axis=1)

# Avoid division by zero
df["% White"] = df["White"] / df["Pop"]
df["% Black"] = df["Black"] / df["Pop"]
df["% Asian"] = df["Asian"] / df["Pop"]
df["% Hispanic"] = df["Hispanic"] / df["Pop"]

# Convert proportions to percentages
df["% White"] = (df["% White"] * 100).round(2)
df["% Black"] = (df["% Black"] * 100).round(2)
df["% Asian"] = (df["% Asian"] * 100).round(2)
df["% Hispanic"] = (df["% Hispanic"] * 100).round(2)

# Preview result
print(df.head())

FileNotFoundError: [Errno 2] No such file or directory: '/mnt/data/Alone_or_in_Any_Combination.csv'

In [116]:
demo_tract.to_csv("/Users/jennifercasavantes/Downloads/demographics_by_tract.csv", index=False)

In [7]:
# Clean the column names to remove white space after the name or in the name
df.columns = df.columns.str.replace(' ', '')
#df.columns = df.columns.str.replace(' ', '_')

In [8]:
df.columns

Index(['GeographicArea-Borough', 'GeographicArea-2010CensusFIPSCountyCode',
       'GeographicArea-NeighborhoodTabulationArea(NTA)*Code',
       'GeographicArea-NeighborhoodTabulationArea(NTA)*Name',
       'TotalPopulation2000Number', 'TotalPopulation2010Number',
       'TotalPopulationChange2000-2010Number',
       'TotalPopulationChange2000-2010Percent'],
      dtype='object')

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
GeographicArea-2010CensusFIPSCountyCode,195.0,54.712821,28.320689,5.0,47.00,61.0,81.000,85.0
TotalPopulation2000Number,195.0,41068.092308,22569.317082,0.0,25635.00,35181.0,54178.500,136954.0
TotalPopulation2010Number,195.0,41923.758974,22282.970575,0.0,26172.00,36891.0,53896.000,132378.0
TotalPopulationChange2000-2010Number,195.0,855.666667,3292.093029,-10329.0,-700.00,455.0,2088.500,19611.0
TotalPopulationChange2000-2010Percent,194.0,5.213918,33.484918,-100.0,-1.85,1.5,6.875,349.5

In [11]:
df[df['GeographicArea-2010CensusFIPSCountyCode'] >= 200000]

Empty DataFrame
Columns: [GeographicArea-Borough, GeographicArea-2010CensusFIPSCountyCode, GeographicArea-NeighborhoodTabulationArea(NTA)*Code, GeographicArea-NeighborhoodTabulationArea(NTA)*Name, TotalPopulation2000Number, TotalPopulation2010Number, TotalPopulationChange2000-2010Number, TotalPopulationChange2000-2010Percent]
Index: []

In [12]:
numeric_columns = df.select_dtypes(['int64', 'float64']).columns
numeric_columns

Index(['GeographicArea-2010CensusFIPSCountyCode', 'TotalPopulation2000Number',
       'TotalPopulation2010Number', 'TotalPopulationChange2000-2010Number',
       'TotalPopulationChange2000-2010Percent'],
      dtype='object')

In [24]:
import pandas as pd

# Step 1: Load your dataset (update the path or URL if needed)
df = pd.read_csv("/Users/jennifercasavantes/Downloads/Census_Demographics_at_the_Neighborhood_Tabulation_Area__NTA__level_20250525.csv")  # Replace with your actual filename

# Step 2: Clean column names (removes spaces, tabs, invisible characters)
df.columns = df.columns.str.strip()

# Step 3: (Optional) See all column names to double-check spelling
print("Column names in dataset:")
print(df.columns.tolist())

# Step 4: Define feature types after cleaning
categorical_cols = [
    'Geographic Area - Borough',
    'Geographic Area - Neighborhood Tabulation Area (NTA)* Name'
]

continuous_cols = [
    'Total Population 2000 Number',
    'Total Population 2010 Number',
    'Total Population Change 2000-2010 Number',
    'Total Population Change 2000-2010 Percent'
]

# Step 5: Print out data types of each group
print("\nCategorical Columns:")
print(df[categorical_cols].dtypes)

print("\nContinuous Columns:")
print(df[continuous_cols].dtypes)

Column names in dataset:
['Geographic Area - Borough', 'Geographic Area - 2010 Census FIPS County Code', 'Geographic Area - Neighborhood Tabulation Area (NTA)* Code', 'Geographic Area - Neighborhood Tabulation Area (NTA)* Name', 'Total Population 2000 Number', 'Total Population 2010 Number', 'Total Population Change 2000-2010 Number', 'Total Population Change 2000-2010 Percent']

Categorical Columns:
Geographic Area - Borough                                     object
Geographic Area - Neighborhood Tabulation Area (NTA)* Name    object
dtype: object

Continuous Columns:
Total Population 2000 Number                 float64
Total Population 2010 Number                 float64
Total Population Change 2000-2010 Number     float64
Total Population Change 2000-2010 Percent    float64
dtype: object